apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-activity-scaler
  labels:
    app.kubernetes.io/name: kubernetes-activity-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-activity-scaler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-activity-scaler
    spec:
      serviceAccountName: kubernetes-activity-scaler
      enableServiceLinks: false
      containers:
      - name: kubernetes-activity-scaler
        image: registry.mwlan.io/mwthink/kubernetes-activity-scaler:latest
        imagePullPolicy: Always
        env:
        - name: WORKLOAD_TYPE
          value: "statefulset" # Can also be "deployment"
        - name: WORKLOAD_NAME
          value: "example-workload"
        - name: WORKLOAD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_TLS_VERIFICATION
          value: "false"
        ports:
        - name: proxy
          containerPort: 3000
          protocol: TCP

